export const iccT20CricketRankingData = {
  mens: [
    {
      position: "1",
      team: "India",
      teamCode: "IND",
      matches: "59",
      points: "15,589",
      rating: "264",
    },
    {
      position: "2",
      team: "England",
      teamCode: "ENG",
      matches: "40",
      points: "10,422",
      rating: "261",
    },
    {
      position: "3",
      team: "Pakistan",
      teamCode: "PAK",
      matches: "50",
      points: "12,719",
      rating: "254",
    },
    {
      position: "4",
      team: "New Zealand",
      teamCode: "NZ",
      matches: "50",
      points: "12,701",
      rating: "254",
    },
    {
      position: "5",
      team: "South Africa",
      teamCode: "SA",
      matches: "33",
      points: "8,278",
      rating: "251",
    },
    {
      position: "6",
      team: "Australia",
      teamCode: "AUS",
      matches: "32",
      points: "7,984",
      rating: "250",
    },
    {
      position: "7",
      team: "West Indies",
      teamCode: "WI",
      matches: "39",
      points: "9,463",
      rating: "243",
    },
    {
      position: "8",
      team: "Sri Lanka",
      teamCode: "SL",
      matches: "37",
      points: "8,774",
      rating: "237",
    },
    {
      position: "9",
      team: "Bangladesh",
      teamCode: "BAN",
      matches: "41",
      points: "9,192",
      rating: "224",
    },
    {
      position: "10",
      team: "Afghanistan",
      teamCode: "AFG",
      matches: "29",
      points: "6,260",
      rating: "216",
    },
    {
      position: "11",
      team: "Zimbabwe",
      teamCode: "ZIM",
      matches: "36",
      points: "7,087",
      rating: "197",
    },
    {
      position: "12",
      team: "Ireland",
      teamCode: "IRE",
      matches: "44",
      points: "8,487",
      rating: "193",
    },
    {
      position: "13",
      team: "Namibia",
      teamCode: "NAM",
      matches: "17",
      points: "3,228",
      rating: "190",
    },
    {
      position: "14",
      team: "Scotland",
      teamCode: "SCO",
      matches: "18",
      points: "3,412",
      rating: "190",
    },
    {
      position: "15",
      team: "UAE",
      teamCode: "UAE",
      matches: "20",
      points: "3,637",
      rating: "182",
    },
    {
      position: "16",
      team: "Netherlands",
      teamCode: "NED",
      matches: "19",
      points: "3,445",
      rating: "181",
    },
    {
      position: "17",
      team: "Nepal",
      teamCode: "NEP",
      matches: "14",
      points: "2,491",
      rating: "178",
    },
    {
      position: "18",
      team: "Hong Kong",
      teamCode: "HK",
      matches: "14",
      points: "2,052",
      rating: "147",
    },
    {
      position: "19",
      team: "Canada",
      teamCode: "CAN",
      matches: "13",
      points: "1,871",
      rating: "144",
    },
    {
      position: "20",
      team: "Oman",
      teamCode: "OMA",
      matches: "13",
      points: "1,823",
      rating: "140",
    },
  ],
  womens: [
    {
      position: "1",
      team: "India",
      teamCode: "IND",
      matches: "59",
      points: "15,589",
      rating: "264",
    },
    {
      position: "2",
      team: "England",
      teamCode: "ENG",
      matches: "40",
      points: "10,422",
      rating: "261",
    },
    {
      position: "3",
      team: "Pakistan",
      teamCode: "PAK",
      matches: "50",
      points: "12,719",
      rating: "254",
    },
    {
      position: "4",
      team: "New Zealand",
      teamCode: "NZ",
      matches: "50",
      points: "12,701",
      rating: "254",
    },
    {
      position: "5",
      team: "South Africa",
      teamCode: "SA",
      matches: "33",
      points: "8,278",
      rating: "251",
    },
    {
      position: "6",
      team: "Australia",
      teamCode: "AUS",
      matches: "32",
      points: "7,984",
      rating: "250",
    },
    {
      position: "7",
      team: "West Indies",
      teamCode: "WI",
      matches: "39",
      points: "9,463",
      rating: "243",
    },
    {
      position: "8",
      team: "Sri Lanka",
      teamCode: "SL",
      matches: "37",
      points: "8,774",
      rating: "237",
    },
    {
      position: "9",
      team: "Bangladesh",
      teamCode: "BAN",
      matches: "41",
      points: "9,192",
      rating: "224",
    },
    {
      position: "10",
      team: "Afghanistan",
      teamCode: "AFG",
      matches: "29",
      points: "6,260",
      rating: "216",
    },
    {
      position: "11",
      team: "Zimbabwe",
      teamCode: "ZIM",
      matches: "36",
      points: "7,087",
      rating: "197",
    },
    {
      position: "12",
      team: "Ireland",
      teamCode: "IRE",
      matches: "44",
      points: "8,487",
      rating: "193",
    },
    {
      position: "13",
      team: "Namibia",
      teamCode: "NAM",
      matches: "17",
      points: "3,228",
      rating: "190",
    },
    {
      position: "14",
      team: "Scotland",
      teamCode: "SCO",
      matches: "18",
      points: "3,412",
      rating: "190",
    },
    {
      position: "15",
      team: "UAE",
      teamCode: "UAE",
      matches: "20",
      points: "3,637",
      rating: "182",
    },
    {
      position: "16",
      team: "Netherlands",
      teamCode: "NED",
      matches: "19",
      points: "3,445",
      rating: "181",
    },
    {
      position: "17",
      team: "Nepal",
      teamCode: "NEP",
      matches: "14",
      points: "2,491",
      rating: "178",
    },
    {
      position: "18",
      team: "Hong Kong",
      teamCode: "HK",
      matches: "14",
      points: "2,052",
      rating: "147",
    },
    {
      position: "19",
      team: "Canada",
      teamCode: "CAN",
      matches: "13",
      points: "1,871",
      rating: "144",
    },
    {
      position: "20",
      team: "Oman",
      teamCode: "OMA",
      matches: "13",
      points: "1,823",
      rating: "140",
    },
  ],
};

export const iccODICricketRankingData = {
  mens: [
    {
      position: "1",
      team: "Australia",
      teamCode: "AUS",
      matches: "27",
      points: "3,112",
      rating: "115",
    },
    {
      position: "2",
      team: "Pakistan",
      teamCode: "PAK",
      matches: "27",
      points: "3,102",
      rating: "115",
    },
    {
      position: "3",
      team: "India",
      teamCode: "IND",
      matches: "40",
      points: "4,558",
      rating: "114",
    },
    {
      position: "4",
      team: "England",
      teamCode: "ENG",
      matches: "28",
      points: "2,942",
      rating: "105",
    },
    {
      position: "5",
      team: "South Africa",
      teamCode: "SA",
      matches: "23",
      points: "2,386",
      rating: "104",
    },
    {
      position: "6",
      team: "New Zealand",
      teamCode: "NZ",
      matches: "31",
      points: "3,110",
      rating: "100",
    },
    {
      position: "7",
      team: "Bangladesh",
      teamCode: "BAN",
      matches: "33",
      points: "3,107",
      rating: "94",
    },
    {
      position: "8",
      team: "Sri Lanka",
      teamCode: "SL",
      matches: "37",
      points: "3,448",
      rating: "93",
    },
    {
      position: "9",
      team: "Afghanistan",
      teamCode: "AFG",
      matches: "21",
      points: "1,687",
      rating: "80",
    },
    {
      position: "10",
      team: "West Indies",
      teamCode: "WI",
      matches: "38",
      points: "2,582",
      rating: "68",
    },
    {
      position: "11",
      team: "Zimbabwe",
      teamCode: "ZIM",
      matches: "30",
      points: "1,641",
      rating: "55",
    },
    {
      position: "12",
      team: "Scotland",
      teamCode: "SCO",
      matches: "33",
      points: "1,662",
      rating: "50",
    },
    {
      position: "13",
      team: "Ireland",
      teamCode: "IRE",
      matches: "24",
      points: "1,052",
      rating: "44",
    },
    {
      position: "14",
      team: "Netherlands",
      teamCode: "NED",
      matches: "28",
      points: "1,044",
      rating: "37",
    },
    {
      position: "15",
      team: "Nepal",
      teamCode: "NEP",
      matches: "42",
      points: "1,446",
      rating: "34",
    },
    {
      position: "16",
      team: "Namibia",
      teamCode: "NAM",
      matches: "28",
      points: "813",
      rating: "29",
    },
    {
      position: "17",
      team: "United States",
      teamCode: "USA",
      matches: "31",
      points: "808",
      rating: "26",
    },
    {
      position: "18",
      team: "Oman",
      teamCode: "OMA",
      matches: "24",
      points: "525",
      rating: "22",
    },
    {
      position: "19",
      team: "UAE",
      teamCode: "UAE",
      matches: "41",
      points: "617",
      rating: "15",
    },
  ],
  womens: [
    {
      position: "1",
      team: "Australia",
      teamCode: "AUS",
      matches: "27",
      points: "3,112",
      rating: "115",
    },
    {
      position: "2",
      team: "Pakistan",
      teamCode: "PAK",
      matches: "27",
      points: "3,102",
      rating: "115",
    },
    {
      position: "3",
      team: "India",
      teamCode: "IND",
      matches: "40",
      points: "4,558",
      rating: "114",
    },
    {
      position: "4",
      team: "England",
      teamCode: "ENG",
      matches: "28",
      points: "2,942",
      rating: "105",
    },
    {
      position: "5",
      team: "South Africa",
      teamCode: "SA",
      matches: "23",
      points: "2,386",
      rating: "104",
    },
    {
      position: "6",
      team: "New Zealand",
      teamCode: "NZ",
      matches: "31",
      points: "3,110",
      rating: "100",
    },
    {
      position: "7",
      team: "Bangladesh",
      teamCode: "BAN",
      matches: "33",
      points: "3,107",
      rating: "94",
    },
    {
      position: "8",
      team: "Sri Lanka",
      teamCode: "SL",
      matches: "37",
      points: "3,448",
      rating: "93",
    },
    {
      position: "9",
      team: "Afghanistan",
      teamCode: "AFG",
      matches: "21",
      points: "1,687",
      rating: "80",
    },
    {
      position: "10",
      team: "West Indies",
      teamCode: "WI",
      matches: "38",
      points: "2,582",
      rating: "68",
    },
    {
      position: "11",
      team: "Zimbabwe",
      teamCode: "ZIM",
      matches: "30",
      points: "1,641",
      rating: "55",
    },
    {
      position: "12",
      team: "Scotland",
      teamCode: "SCO",
      matches: "33",
      points: "1,662",
      rating: "50",
    },
    {
      position: "13",
      team: "Ireland",
      teamCode: "IRE",
      matches: "24",
      points: "1,052",
      rating: "44",
    },
    {
      position: "14",
      team: "Netherlands",
      teamCode: "NED",
      matches: "28",
      points: "1,044",
      rating: "37",
    },
    {
      position: "15",
      team: "Nepal",
      teamCode: "NEP",
      matches: "42",
      points: "1,446",
      rating: "34",
    },
    {
      position: "16",
      team: "Namibia",
      teamCode: "NAM",
      matches: "28",
      points: "813",
      rating: "29",
    },
    {
      position: "17",
      team: "United States",
      teamCode: "USA",
      matches: "31",
      points: "808",
      rating: "26",
    },
    {
      position: "18",
      team: "Oman",
      teamCode: "OMA",
      matches: "24",
      points: "525",
      rating: "22",
    },
    {
      position: "19",
      team: "UAE",
      teamCode: "UAE",
      matches: "41",
      points: "617",
      rating: "15",
    },
  ],
};
export const iccTestCricketRankingData = {
  mens: [
    {
      position: "1",
      team: "India",
      teamCode: "IND",
      matches: "29",
      points: "3,434",
      rating: "118",
    },
    {
      position: "2",
      team: "Australia",
      teamCode: "AUS",
      matches: "30",
      points: "3,534",
      rating: "118",
    },
    {
      position: "3",
      team: "England",
      teamCode: "ENG",
      matches: "43",
      points: "4,941",
      rating: "115",
    },
    {
      position: "4",
      team: "South Africa",
      teamCode: "SA",
      matches: "21",
      points: "2,182",
      rating: "104",
    },
    {
      position: "5",
      team: "New Zealand",
      teamCode: "NZ",
      matches: "23",
      points: "2,291",
      rating: "100",
    },
    {
      position: "6",
      team: "Pakistan",
      teamCode: "PAK",
      matches: "25",
      points: "2,304",
      rating: "92",
    },
    {
      position: "7",
      team: "Sri Lanka",
      teamCode: "SL",
      matches: "27",
      points: "2,123",
      rating: "79",
    },
    {
      position: "8",
      team: "West Indies",
      teamCode: "WI",
      matches: "28",
      points: "2,154",
      rating: "77",
    },
    {
      position: "9",
      team: "Bangladesh",
      teamCode: "BAN",
      matches: "19",
      points: "873",
      rating: "46",
    },
    {
      position: "10",
      team: "Zimbabwe",
      teamCode: "ZIM",
      matches: "7",
      points: "223",
      rating: "32",
    },
  ],
  womens: [
    {
      position: "1",
      team: "India",
      teamCode: "IND",
      matches: "29",
      points: "3,434",
      rating: "118",
    },
    {
      position: "2",
      team: "Australia",
      teamCode: "AUS",
      matches: "30",
      points: "3,534",
      rating: "118",
    },
    {
      position: "3",
      team: "England",
      teamCode: "ENG",
      matches: "43",
      points: "4,941",
      rating: "115",
    },
    {
      position: "4",
      team: "South Africa",
      teamCode: "SA",
      matches: "21",
      points: "2,182",
      rating: "104",
    },
    {
      position: "5",
      team: "New Zealand",
      teamCode: "NZ",
      matches: "23",
      points: "2,291",
      rating: "100",
    },
    {
      position: "6",
      team: "Pakistan",
      teamCode: "PAK",
      matches: "25",
      points: "2,304",
      rating: "92",
    },
    {
      position: "7",
      team: "Sri Lanka",
      teamCode: "SL",
      matches: "27",
      points: "2,123",
      rating: "79",
    },
    {
      position: "8",
      team: "West Indies",
      teamCode: "WI",
      matches: "28",
      points: "2,154",
      rating: "77",
    },
    {
      position: "9",
      team: "Bangladesh",
      teamCode: "BAN",
      matches: "19",
      points: "873",
      rating: "46",
    },
    {
      position: "10",
      team: "Zimbabwe",
      teamCode: "ZIM",
      matches: "7",
      points: "223",
      rating: "32",
    },
  ],
};
